server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
  servlet:
    context-path: /
    session:
      timeout: 300
spring:
  devtools:
    restart:
      exclude: static/**
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  mvc:
    favicon:
      enabled: false
scheduleService:
  getInfoOne:
    fixedRateString: 600
  getInfoTwo:
    cron: 0/1 * * * * ?
